config/routes.rb
MusicApp::Application.routes.draw do
  resources :users

  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:new, :show]
  end

  resources :notes, except: [:new, :show]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, presence: :true
  validates :recording_style, inclusion: ["Studio", "Live"]

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: :true

  has_many :albums, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, presence: :true

  belongs_to :user

  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, presence: :true

  belongs_to :album

  has_many :notes
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  # validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :notes

  def self.generate_session_token # why make this a class method?
    SecureRandom.base64
  end

  def self.find_by_credentials(email, password)
    user = self.find_by_email(email)
    return nil if user.nil?

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
    self.save
    self.session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :ensure_log_in

  def new
    @album = Album.new
    @band = Band.find(params[:band_id])
    @bands = Band.all

    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
  end

  def edit
    @album = Album.find(params[:id])
    @band = @album.band
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if Album.update(@album, album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to band_url(@album.band)
  end

  private

  def album_params
    self.params.require(:album).permit(:name, :band_id, :recording_style)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def log_in!(user)
    user.reset_session_token!
    token = user.session_token
    session[:session_token] = token
    @current_user = user
  end

  def logged_in?
    return nil if current_user.nil?

    current_user.session_token == session[:session_token]
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def ensure_log_in
    unless logged_in?
      flash[:notice] = "Sorry, you have to be logged in to do that."
      redirect_to new_session_url
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :ensure_log_in

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if Band.update(@band, band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    redirect_to bands_url
  end

  private

  def band_params
    self.params.require(:band).permit(:name)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @track = Track.find(params[:track_id])
    @note = Note.new
    render :new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @track = Track.find(params[:track][:id])
    @note.track_id = @track.id
    @note.save

    redirect_to track_url(@track)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def note_params
    self.params.require(:note).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    email = params[:user][:email]
    password = params[:user][:password]
    @user = User.find_by_credentials(email, password)

    if @user.nil?
      render :new
    else
      log_in!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    log_out!

    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :ensure_log_in

  def new
    @track = Track.new
    @album = Album.find(params[:album_id])
    @albums = Album.all

    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    @album = @track.album
    @albums = Album.all

    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if Track.update(@track, track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    redirect_to album_url(@track.album)
  end

  private

  def track_params
    self.params.require(:track).permit(:name, :album_id, :status, :lyrics)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user) # in ApplicationController
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    self.params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
             name="authenticity_token"
             value="#{ form_authenticity_token }">
    HTML
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% if album.persisted? %>
  <% target_url = album_url(album) %>
  <% request_type = "PATCH" %>
  <% button_message = "Save Changes" %>
<% else %>
  <% target_url = albums_url %>
  <% request_type = "POST" %>
  <% button_message = "Create Album" %>
<% end %>

<form action="<%= target_url %>" method="POST">
  <%= auth_token %>

  <input type="hidden" name="_method" action=<%= request_type %>>

  <label for="album_name">Name</label>
  <input type="text"
         name="album[name]"
         id="album_name"
         value="<%= album.name %>">
  <br><br>

  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="album_band_id">
  <% bands.each do |band| %>

    <option value="<%= band.id %>"
      <% if band == source_band %>selected="selected"<% end %>>
      <%= band.name %>
    </option>

  <% end %>
  </select>
  <br><br>

  <input type="radio"
         name="album[recording_style]"
         id="album_recording_style"
         value="Studio">
  <label id="album_recording_style">Studio</label>

  <input type="radio"
         name="album[recording_style]"
         id="album_recording_style"
         value="Live">
  <label id="album_recording_style">Live</label>
  <br><br>

  <input type="Submit" value="<%= button_message %>">
</form>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", bands: @bands, source_band: @band, album: @album %>

app/views/albums/new.html.erb
<h1>Add an Album</h1>

<%= render "form", bands: @bands, source_band: @band, album: @album %>

<!-- <form action="<%= new_band_album_url %>" method="POST">
  <%= auth_token %>

  <label for="album_name">Name</label>
  <input type="text" name="album[name]" id="album_name">
  <br><br>

  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="album_band_id">
  <% @bands.each do |band| %>

    <option value="<%= band.id %>"
      <% if band == @band %>selected="selected"<% end %>>
      <%= band.name %>
    </option>

  <% end %>
  </select>
  <br><br>

  <input type="radio"
         name="album[recording_style]"
         id="album_recording_style"
         value="Studio">
  <label id="album_recording_style">Studio</label>

  <input type="radio"
         name="album[recording_style]"
         id="album_recording_style"
         value="Live">
  <label id="album_recording_style">Live</label>

  <input type="Submit" value="Create Album">
</form> -->

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<%= button_to "Edit", edit_album_url(@album), method: :get %>
<%= button_to "Delete", album_url(@album), method: :delete %>
<br>

Tracks: <br>
<% @album.tracks.each do |track| %>

  <a href="<%= track_url(track) %>">
    <%= track.name %>
  </a>
  <br>

<% end %>
<br>

<%= button_to "Add track", new_album_track_url(@album), method: :get %>
<br>

<a href="<%= band_url(@band) %>">
  Back to '<%= @band.name %>'
</a>

app/views/bands/_form.html.erb
<% if band.persisted? %>
  <% target_url = band_url(band) %>
  <% request_type = "PATCH" %>
  <% button_message = "Save Changes" %>
<% else %>
  <% target_url = bands_url %>
  <% request_type = "POST" %>
  <% button_message = "Create Band" %>
<% end %>

<form action="<%= target_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= request_type %>">

  <%= auth_token %>

  <label for=band_name>Name</label>
  <input type="text" name="band[name]" id="band_name" value="<%= @band.name %>">

  <br>

  <input type="submit" value="<%= button_message %>">

</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands</h1>

<% @bands.each do |band| %>

  <a href="<%= band_url(band) %>"><%= band.name %></a>
  <br>

<% end %>

<br><br>

<%= button_to "Add another band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>Add a Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<%= button_to "Edit", edit_band_url(@band), method: :get %>
<%= button_to "Delete", band_url(@band), method: :delete %>
<br>

Albums: <br>
<% @band.albums.each do |album| %>

  <a href="<%= album_url(album) %>">
    <%= album.name %>
  </a>
  <br>

<% end %>
<br>

<%= button_to "Add album", new_band_album_url(@band), method: :get %>
<br>

<a href="<%= bands_url %>">Back to band list</a>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= current_user.email %>
  <%= button_to "Log out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_url %>
  or
  <%= link_to "Sign in", new_session_url %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
</head>
<body>

  <%= render "layouts/header" %>

  <%= yield %>

  <%= flash[:notice] if flash[:notice] %>

</body>
</html>

app/views/notes/new.html.erb
<h1>Write a New Note</h1>

<form action="<%= notes_url %>" method="POST">
  <%= auth_token %>

  <textarea name="note[content]" value="<%= @note.content %>">
  </textarea>
  <br><br>
  
  <input type="hidden" name="track[id]" value="<%= @track.id %>">

  <input type="submit" value="Publish Note" >

</form>

app/views/tracks/_form.html.erb
<% if track.persisted? %>
  <% target_url = track_url(track) %>
  <% request_type = "PATCH" %>
  <% button_message = "Save Changes" %>
<% else %>
  <% target_url = tracks_url %>
  <% request_type = "POST" %>
  <% button_message = "Create Track" %>
<% end %>

<form action="<%= target_url %>" method="POST">
  <%= auth_token %>

  <input type="hidden" name="_method" action=<%= request_type %>>

  <label for="track_name">Name</label>
  <input type="text"
         name="track[name]"
         id="track_name"
         value="<%= track.name %>">
  <br><br>

  <label for="track_album_id">Album</label>
  <select name="track[album_id]" id="track_album_id">
  <% albums.each do |album| %>

    <option value="<%= album.id %>"
      <% if album == source_album %>selected="selected"<% end %>>
      <%= album.name %>
    </option>

  <% end %>
  </select>
  <br><br>

  <input type="radio"
         name="track[status]"
         id="track_status"
         value="Regular track">
  <label id="track_status">Regular track</label>

  <input type="radio"
         name="track[status]"
         id="track_status"
         value="Bonus track">
  <label id="album_recording_style">Bonus track</label>
  <br><br>

  <input type="Submit" value="<%= button_message %>">
</form>

app/views/tracks/_notes.html.erb
<h4>Notes:</h4>

<% @track.notes.each do |note| %>
  "<%= note.content %> "
  <br>
  Posted by <%= note.user.email %> at <%= note.created_at %>
  <br><br>
<% end %>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render "form", track: @track, source_album: @album, albums: @albums %>

app/views/tracks/new.html.erb
<h1>Add a New Track</h1>

<%= render "form", track: @track, source_album: @album, albums: @albums %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<%= button_to "Edit", edit_track_url(@track), method: :get %>
<%= button_to "Delete", track_url(@track), method: :delete %>


<form action="<%= track_url(@track) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>

  <label for="track_lyrics">Lyrics:</label>
  <textarea name="track[lyrics]" id="track_lyrics">
    <%= @track.lyrics %>
  </textarea>

  <input type="submit" value="Publish">

</form>
<br><br>

<%= render "notes" %>

<br>
<a href="<%= new_track_note_url(@track) %>">
  Write a new note for this track
</a>
<br><br>

<%= button_to "Add another track", new_album_track_url(@album), method: :get %>
<br><br>

<a href="<%= album_url(@album) %>">
  Back to '<%= @album.name %>'
</a>
<br><br>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<form action="<%= users_url %>", method="POST">

  <%= auth_token %>

  <label for="user_email">Email Address</label>
  <input type="text"
         name="user[email]"
         id="user_email"
         value="<%= @user.email %>">

  <br>

  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_email">

  <br>

  <input type="submit" value="Make My Account">

</form>

app/views/users/show.html.erb
<br>
Welcome, <%= @user.email %>!
<br><br>

<a href="<%= bands_url %>">See all bands</a>